### ISSUE TITLE
[BUG] OnVehicleRespray Doens't get called in Pay n spray 

### ISSUE THREAD

**Issue by Jexuul** [openmultiplayer/server-beta-old#150]

**Comment by Alasnkz** [comment]
SA:MP doesn't have this either. `Misleadingly, this callback is not called for pay 'n' spray (only modshops).`

Possibly a thing for the fixes component though.

**Comment by Jexuul** [comment]
by the name of it, it should also be called in pay n spray

**Comment by NexiusTailer** [comment]
> by the name of it, it should also be called in pay n spray

It doesn't sent by a client, so you cannot really "fix" it from the server side (there's no any rpc from client and thus nothing wrong from the server part). Emulating its call by checking player's vehicle health changing being in range of pay'n'spray points is the only kludge you can do, but still not a proper fix, just like with calling this callback only when a player exits the modshop instead of calling when he really change his vehicle color being inside it - also client issue.
