### ISSUE TITLE
[COMPATIBILITY]: Win32 only

### ISSUE THREAD

**Issue by Disinterpreter** [openmultiplayer/server-beta-old#16]
# Description

Win32 only, 2022 guys

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

1. Start a server
2. Look at task manager
3. ![image](https://user-images.githubusercontent.com/3816155/164402406-989bd194-9981-4547-9226-c22132526ab1.png)

# open.mp server version

latest (20/04/2022 - 17:00 build)

# Operating system or distribution

Windows 10

**Comment by AmyrAhmady** [comment]
Pawn VM doesn't run on a x64 host, we are forced to do that reason at the moment.
oepn.mp can be and will be built for x64 without Pawn component on public release separately because you can easily adopt other languages or only use our C++ SDK, but right now for beta testing (which involves people's scripts, Pawn is needed)

**Comment by Hual** [comment]
> Pawn VM doesn't run on a x64 host, we are forced to do that reason at the moment. oepn.mp can be and will be built for x64 without Pawn component on public release separately because you can easily adopt other languages or only use our C++ SDK, but right now for beta testing (which involves people's scripts, Pawn is needed)

To add to this, we've made a breakthrough in running 32-bit pawn in 64-bit mode so there *might* be hope

**Comment by Disinterpreter** [comment]
> Pawn VM doesn't run on a x64 host, we are forced to do that reason at the moment. oepn.mp can be and will be built for x64 without Pawn component on public release separately because you can easily adopt other languages or only use our C++ SDK, but right now for beta testing (which involves people's scripts, Pawn is needed)

Not an answer, if we talk about Windows, it's okay. But if we talk about Linux. Running i686 software on linux is really contains more workarounds than executing `./server`, plus if we do a docker, we need to find i686 image or enabling compatibility.

So, I should ask to high priority to this issue, please. (only IMHO)

**Comment by AmyrAhmady** [comment]
How is this not an answer? how else are we supposed to run 15 years worth of pawn scripts when we promised backward compatibility?

And like I said, open.mp x64 is already an option, it just doesn't have pawn anymore, only C++ SDK

**Comment by Disinterpreter** [comment]
> How is this not an answer? how else are we supposed to run 15 years worth of pawn scripts when we promised backward compatibility?
> 
> And like I said, open.mp x64 is already an option, it just doesn't have pawn anymore, only C++ SDK

As I remember Cortez's pawn works fine in x64, moreover when we discussed in past, you assured me that it can work in different architectures(like modern ARM), as a result, you can't run it on x64 =\

Running server in 2022 on i686 is really bad.

**Comment by NexiusTailer** [comment]
> > How is this not an answer? how else are we supposed to run 15 years worth of pawn scripts when we promised backward compatibility?
> > And like I said, open.mp x64 is already an option, it just doesn't have pawn anymore, only C++ SDK
> 
> As I remember Cortez's pawn works fine in x64, moreover when we discussed in past, you assured me that it can work in different architectures(like modern ARM), as a result, you can't run it on x64 =\

So, maybe it's worth sharing a link to that fork? I think there's just a few people know that it ever existed.

**Comment by AmyrAhmady** [comment]
> > How is this not an answer? how else are we supposed to run 15 years worth of pawn scripts when we promised backward compatibility?
> > And like I said, open.mp x64 is already an option, it just doesn't have pawn anymore, only C++ SDK
> 
> As I remember Cortez's pawn works fine in x64, moreover when we discussed in past, you assured me that it can work in different architectures(like modern ARM), as a result, you can't run it on x64 =\
> 
> Running server in 2022 on i686 is really bad.

If Daniel's pawn can be used in a x64 host then why not
But again I don't understand this why you are sad or mad about it, open.mp is not 32bit only

Like I said, we will release literally different versions for different archs, for ARM, x86 and x64, so what's the problem?

**Comment by Disinterpreter** [comment]
Issues should close after completing, I suppose, may we consider it like you shall never do that?

**Comment by AmyrAhmady** [comment]
@Disinterpreter Here, I reopened it
It was closed because you didn't answer, and because I said IT IS HAPPENING

but tell me which part of me saying
"Like I said, we will release literally different versions for different archs, for ARM, x86 and x64, so what's the problem?"
is not satisfying to you?

You asked for x64 and I literally said it will happen on release, but not with beta, because is meant to be for testing 15 years worth of samp resources (scripts and plugins, all made with being 32bit in mind)
You can't just drop it with Pawn x64 on beta when you want to find test core features
no one on earth knows how unstable Pawn x64 is, and no one knows if it's even going to work, so why would I want to test my script with a platform that may even have way deeper issues that is going to be hard for debug, when we just want to fix current issues in core implementations!??

Like I said, open.mp x64 is already a thing and it will be available on Release, you made an issue and said "Win32 only, 2022 guys", so I guess I covered your initial not-question but salty statement with that
It's not our fault Pawn x64 is broken and has many unknown behaviors, people made their scripts from 2005 on SA:MP that remained 32bit, open.mp is meant to be working with those

So yes, now I'm closing it
repeating again

Your issue: open.mp being 32bit only
My answer: it will have other versions on stable release with other architectures, just not with beta because we want to find core issues, not facing unknown Pawn x64 behaviors because it's broken and it was never tested properly
Thanks
