### ISSUE TITLE
[BUG]: вывод во внешку

### ISSUE THREAD

**Issue by SantiagoBoss1** [openmultiplayer/server-beta-old#69]
Короче, я запустил сервер, открыл порты, дал ип другу, и не работает у него сервер, а когда я запускаю мод с обычного запускатора самп, то всё работает

**Comment by ArTDsL** [comment]
`Translated Question`
To resume my situation: i run the server, open the required ports and send the ip address to a friend. Server won't work for him...
When i start the mod using samp launcher everything works fine!

### ANSWER (Отвечать)

`Отвечать`
Ола, @SantiagoBoss1! Проверьте следующие итенс:
1 - Open.mp разрешен в брандмауэре;
2 - Активация прямого порта 7777;
3 - Ваш игровой мод "переведен" на open.mp;
4 - параметры запуска вашего сервера верны;

Если можно, выложите фото консоли!

___

`Translated answer`
1 - Open.mp is allowed in the firewall;
2 - Port 7777 is open;
3 - Your game mod is "translated" to open.mp;
4 - Your server startup parameters are correct;

Post a picture of the console if you can!

**Comment by SantiagoBoss1** [comment]
1. Браудмер отключён он не как не может блокировать open mp
2. Всё проверял, всё активировано
3. Я взял мод даймонда и запихал туда omp-server.exe 
4. все верно перепроверял и переписывал

**Comment by ArTDsL** [comment]
`Translated answer`
1. Firewall is disable, can't be him blocking the connection to open.mp;
2. Double check, everything is in order;
3. I get the "diamond" gamemode and stuffed into omp-server.exe;
4. Everything is checked and correct;

<hr>

### QUESTION AND ANSWER (Вопрос и ответ)
Кажется, проблема в вашем игровом режиме или в вашем интернет-соединении...

Игровые моды open.mp немного отличаются от SA-MP, полная совместимость пока не 100%!

Сделайте 2 теста:
1. Проверьте, можете ли ВЫ подключиться и играть (попробуйте поиграть около 5 минут и проверьте некоторые функции, чтобы проверить свой игровой режим).
2. Проверьте, может ли [этот веб-сайт](https://www.yougetsignal.com/tools/open-ports/) открыть ваш порт соединения 7777 (если возврат "CLOSED", ваш маршрутизатор должен быть переконфигурирован).
3. И, наконец, отправьте изображение вашего работающего omp-server.exe.
<br>

`Translated Question`
Seems the problem is someway your gamemode or your internet connection...
open.mp gamemodes are a little different from SA-MP, full compatibility are not 100% yet!
Make 2 tests:
1 - Check if YOU can connect and play (try to play for about 5 minutes and check some functionalities to test your game mode).
2 - Check if [this website](https://www.yougetsignal.com/tools/open-ports/) can find your connection port 7777 opened (if return is "CLOSED" them your router need reconfiguration).
3 -  Finnaly, send a picture of your omp-server.exe running.

**Comment by SantiagoBoss1** [comment]
ща проверю

**Comment by ArTDsL** [comment]
`Translated answer`
I'll check

## ANSWER (Отвечать)
Дайте мне знать что-нибудь!
<br>
`Translated answer`
Let me know anything!

**Comment by ArTDsL** [comment]
@Hual or @AmyrAhmady **CLOSED** i think ^^/

**Comment by continue98** [comment]
> 1. Браудмер отключён он не как не может блокировать open mp
> 
>     2. Всё проверял, всё активировано
> 
>     3. Я взял мод даймонда и запихал туда omp-server.exe
> 
>     4. все верно перепроверял и переписывал

You probably need netmap ([port forwarding](https://en.wikipedia.org/wiki/Port_forwarding)) on your router
